### ISSUE TITLE
[Feature] Cookies & Sessions for React/Express Application

### ISSUE THREAD

**Issue by david-zou** [Ryxias/chuuni#67]
As of now, the React site has no way of keeping track of states when the user leaves the site or refreshes.  To retain the user's states (i.e. shopping cart, personal profiles), the site must utilize cookies and sessions.  To do so, we will be using the express-session middleware as our application already makes uses of Express in our node server.  This issue documentation will be further updated in the future as more ideas come in.

### Resources 
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie
* https://github.com/expressjs/session#cookie
* https://www.npmjs.com/package/express-mysql-session

**Comment by Ryxias** [comment]
I fixed this a while ago, forgot to cc the PR
